version: "3.8"

services:
  sollu-pos-client:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    container_name: sollu-pos-client
    restart: always
    ports:
      - "8003:80"
    env_file:
      - .env
